export const FETCH_CATEGORYLIST='FETCH_CATEGORYLIST'
export const FETCH_SPACE_DETAIL='FETCH_SPACE_DETAIL'
export const FETCH_SPACELIST='FETCH_SPACELIST'
export const FETCH_SPACEFINDREACT='FETCH_SPACEFINDREACT'
export const FETCH_SPACEPAGEREACT='FETCH_SPACEPAGEREACT'


export const FETCH_FOOD_LOCATION='FETCH_FOOD_LOCATION'
export const FETCH_NEWS='FETCH_NEWS'
export const FETCH_PAGE='FETCH_PAGE'